version: "3.9"

services:
  server:
   build: .
   ports:
    - "2000:2000"


  mongodb:
    container_name: simulatebanks-db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db